### ISSUE TITLE
Color picker no longer opens

### ISSUE THREAD

**Issue by samrgray** [KevinGutowski/keyColor#2]
In Sketch 53, after applying a color to an object with the plugin, the color picker no longer opens normally from the inspector while that object is selected. Only the caret from the top of the popup is visible. Selecting a different object (which has never had its color set by the plugin) and opening the color picker works normally.
![screen shot 2019-02-05 at 11 39 50 am](https://user-images.githubusercontent.com/1806924/52288981-290c6c00-293b-11e9-8d5c-524b8f16ec73.png)

**Comment by KevinGutowski** [comment]
Woah how bizarre! I’ll take a look. Are you still have this issue @samrgray?

**Comment by samrgray** [comment]
No longer since updating to Sketch 54!

**Comment by KevinGutowski** [comment]
Sweet - sorry for the late reply. Notifications on GitHub confuse me 🙃
